import {React,h,C,$,go,A,useLS,useHash,useState,useEffect,useContext} from '../lib/helpers.js';
import {artUri,kindOf} from './art.js';
import {CATS,LOCS,STATES,sn,F,R,COUP,OFFERS,doSearch,calc,catImg} from '../data/catalog.js';
const TRY_REAL=true;
function Photo({src,alt,cls=''}){const[real,setReal]=useState(TRY_REAL);useEffect(()=>{setReal(TRY_REAL)},[src]);const u=real?src:artUri(kindOf(src,alt),alt);
return h('div',{className:'ph '+cls},h('img',{key:u,src:u,alt,loading:'lazy',onError:()=>setReal(false)}))}
const Dot=({v})=>h('span',{className:'dot '+(v?'v':'n'),title:v?'Veg':'Non-veg'}),Rate=({v})=>h('span',{className:'rate'},'★ '+v);
const Sec=({t,to,children})=>h('section',{className:'sec wrap'},h('div',{className:'row sp'},h('h2',null,t),to&&A(to,{className:'tag'},'See all →')),children);
function Empty({big='!',t,d,to,b}){return h('div',{className:'empty'},h('div',{className:'big'},big),h('h2',null,t),h('p',{className:'mut'},d),to&&h('button',{className:'btn',onClick:()=>go(to)},b))}
function Add({f,r}){const{cart,add,chg}=useContext(C),q=cart.rid===r.id?cart.items[f.id]||0:0;return q?h('div',{className:'qty'},h('button',{onClick:()=>chg(f.id,-1)},'−'),h('b',null,q),h('button',{onClick:()=>chg(f.id,1)},'+')):h('button',{className:'btn sm out',disabled:!r.open,onClick:()=>add(f,r)},'ADD')}
function FoodCard({f,r}){const{favs,fav}=useContext(C);return h('div',{className:'card food'},h('div',{style:{position:'relative'}},h(Photo,{src:f.img,alt:f.n}),+f.rt>=4.7&&h('span',{className:'bs'},'Bestseller'),h('button',{className:'heart','aria-label':'Favourite',onClick:()=>fav('f',f.id)},favs.f.includes(f.id)?'♥':'♡')),h('div',{className:'pad'},h('div',{className:'row'},h(Dot,{v:f.veg}),h(Rate,{v:f.rt})),h('h4',null,f.n),h('p',{className:'mut'},f.d),h('div',{className:'row sp'},h('b',null,$(f.p)),h(Add,{f,r}))))}
function Dish({f}){const[o,setO]=useState(false),{favs,fav}=useContext(C),rs=R.filter(r=>r.cats.includes(f.cat));return h('div',{className:'card'},h('div',{style:{position:'relative'}},h(Photo,{src:f.img,alt:f.n}),+f.rt>=4.7&&h('span',{className:'bs'},'Bestseller'),h('button',{className:'heart',onClick:()=>fav('f',f.id)},favs.f.includes(f.id)?'♥':'♡')),h('div',{className:'pad'},h('div',{className:'row'},h(Dot,{v:f.veg}),f.st&&h('span',{className:'tag'},sn(f.st))),h('h4',null,f.n),h('div',{className:'row sp'},h('b',null,$(f.p)),h('button',{className:'btn sm',onClick:()=>setO(!o)},o?'Hide':'Order from…')),o&&h('div',{className:'sub'},rs.map(r=>h('div',{key:r.id,className:'row sp ri'},h('div',null,A('/restaurant/'+r.id,null,h('b',null,r.name)),h('div',{className:'mut'},`★ ${r.rating} · ${r.time} min`+(r.open?'':' · Closed'))),h(Add,{f,r}))))))}
function RestCard({r}){const{favs,fav}=useContext(C);return h('div',{className:'card',style:r.open?null:{opacity:.6}},h('div',{style:{position:'relative'}},A('/restaurant/'+r.id,null,h(Photo,{src:r.img,alt:r.name})),r.offer&&h('div',{className:'ov'},r.offer),h('span',{className:'tm'},r.open?r.time+' min':'Closed'),h('button',{className:'heart',onClick:()=>fav('r',r.id)},favs.r.includes(r.id)?'♥':'♡')),h('div',{className:'pad'},h('div',{className:'row sp'},h('h4',null,r.name),h(Rate,{v:r.rating})),h('div',{className:'mut'},r.cuisine+' · '+r.n+' ratings'),h('div',{className:'row mut'},r.pv?h(Dot,{v:1}):[r.nv&&h(Dot,{key:'n',v:0}),h(Dot,{key:'v',v:1})],`${r.open?r.time+' min':'Closed'} · ${r.dist} km · ${$(r.two)} for two`),r.offer&&h('div',{style:{margin:'6px 0'}},h('span',{className:'tag'},'🏷 '+r.offer)),h('button',{className:'btn sm dk full',onClick:()=>go('/restaurant/'+r.id)},'View Menu')))}
function SearchBar({init=''}){const[q,setQ]=useState(init),[o,setO]=useState(false),sg=q?[...new Set([...CATS,...F.map(x=>x.n),...R.map(x=>x.name)].filter(s=>s.toLowerCase().includes(q.toLowerCase())))].slice(0,6):[],run=s=>{setQ(s);setO(false);go('/search/'+encodeURIComponent(s))};
return h('div',{className:'sb'},h('form',{onSubmit:e=>{e.preventDefault();q.trim()&&run(q.trim())}},h('input',{value:q,'aria-label':'Search',placeholder:'Search biryani, pizza, restaurants…',onChange:e=>{setQ(e.target.value);setO(true)},onFocus:()=>setO(true),onBlur:()=>setTimeout(()=>setO(false),150)}),q&&h('button',{type:'button',className:'x','aria-label':'Clear',onClick:()=>setQ('')},'✕'),h('button',{className:'btn'},'Search')),o&&sg.length>0&&h('ul',{className:'sg'},sg.map(s=>h('li',{key:s,onMouseDown:()=>run(s)},'🔍 '+s))))}

export {Photo,Dot,Rate,Sec,Empty,Add,FoodCard,Dish,RestCard,SearchBar};
